name: ohana_webapp_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.0
  carousel_slider: ^4.2.1
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
  url_launcher: ^6.0.20
  flutter_quill: ^9.3.11
  transformable_list_view: ^0.5.0
  firebase_core: ^3.1.0
  cloud_firestore: ^5.0.1 
  google_maps_flutter: ^2.7.0
  flutter_polyline_points: ^2.0.0
  location: ^6.0.2
  file_picker: ^8.0.5
  dotted_border: ^2.1.0
  firebase_storage: ^12.0.1
  video_player: ^2.9.1
  chewie: ^1.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  google_fonts: ^6.2.1
  flutter_bloc: ^8.0.0


flutter:
  uses-material-design: true
  assets :
    - assets/
    - assets/homepage_image/
    - assets/services_images/
    - assets/social_media_icons/
    - assets/services_icons/cyber_services/
    - assets/services_icons/dev_services/
    - assets/services_images/dev_services/
    - assets/services_images/cyber_services/
    - assets/services_images/dev_services/web/
    - assets/about_us_image/
    - assets/logo_partners/
    - assets/blog_images/
    - assets/offers_images/
    - assets/alert_svg/
    - assets/offers_svg/
    - assets/alert_images/
    - assets/values_icons/
    - assets/services_images/dev_services/software_services/
    - assets/services_images/dev_services/software_services/carousel_images/
